from sqlalchemy import Column, Integer, String, Float, Boolean, ForeignKey, Date, JSON
from .base import Base

class MedicalReport(Base):
    __tablename__ = "medical_reports"
    
    id = Column(Integer, primary_key=True, index=True, comment="主键ID")
    username = Column(String(50), ForeignKey("user.username"), index=True, comment="用户名（外键关联user表）")
    subject_identifier = Column(String(255), index=True, comment="受试者标识符")
    age = Column(Float, comment="年龄")
    sex = Column(String(10), comment="性别")
    male = Column(Boolean, comment="是否为男性")
    height = Column(Float, comment="身高")
    weight = Column(Float, comment="体重")
    BMI = Column(Float, comment="体重指数")
    trestbps = Column(String(32), comment="静息血压")
    sysBP = Column(Float, comment="收缩压")
    diaBP = Column(Float, comment="舒张压")
    ap_hi = Column(Float, comment="收缩压（另一种表示）")
    ap_lo = Column(Float, comment="舒张压（另一种表示）")
    heartRate = Column(Float, comment="心率")
    thalach = Column(Float, comment="最大心率")
    chol = Column(Float, comment="胆固醇")
    totChol = Column(Float, comment="总胆固醇")
    cholest = Column(Float, comment="胆固醇（另一种表示）")
    High_LDL = Column(Float, comment="高 LDL 胆固醇")
    Low_HDL = Column(Float, comment="低 HDL 胆固醇")
    fbs = Column(Float, comment="空腹血糖")
    gluc = Column(Float, comment="血糖（另一种表示）")
    glucose = Column(Float, comment="血糖")
    anemia = Column(Boolean, comment="是否贫血")
    creatinin = Column(Float, comment="肌酐")
    platelets = Column(Float, comment="血小板")
    serum_creatinine = Column(Float, comment="血清肌酐")
    sodium = Column(Float, comment="钠")
    ejection = Column(Float, comment="射血分数")
    Quantum = Column(Float, comment="量子（可能是某种指标）")
    smoke = Column(Boolean, comment="是否吸烟")
    currentSmok = Column(Boolean, comment="当前是否吸烟")
    cigsPerDay = Column(Float, comment="每天吸烟数量")
    alco = Column(Boolean, comment="是否饮酒")
    Alcohol = Column(Float, comment="饮酒量")
    BPMeds = Column(Boolean, comment="是否服用降压药")
    diabetes = Column(Boolean, comment="是否有糖尿病")
    high_blood_pressure = Column(Boolean, comment="是否有高血压")
    active = Column(Boolean, comment="是否活跃")
    Exercise = Column(Boolean, comment="是否锻炼")
    Family_History = Column(Boolean, comment="是否有家族病史")
    No_Diseases = Column(Boolean, comment="是否无疾病")
    stress = Column(Float, comment="压力水平")
    Sleep = Column(Float, comment="睡眠质量")
    sugar = Column(Float, comment="糖摄入量")
    diet = Column(Float, comment="饮食质量")
    obesity = Column(Boolean, comment="是否肥胖")
    cp = Column(Integer, comment="胸痛类型")
    restecg = Column(Integer, comment="静息心电图结果")
    exang = Column(Boolean, comment="运动诱发心绞痛")
    oldpeak = Column(Float, comment="ST段压低")
    slope = Column(Integer, comment="运动ST段斜率")
    ca = Column(Integer, comment="主要血管数量")
    thal = Column(Integer, comment="地中海贫血")
    subject = Column(String(255), comment="受试者")
    segment1 = Column(Float, comment="第一导联段")
    segment2 = Column(Float, comment="第二导联段")
    segment3 = Column(Float, comment="第三导联段")
    segment4 = Column(Float, comment="第四导联段")
    Num = Column(Integer, comment="数量")
    target = Column(Boolean, comment="目标变量（是否有心脏病）")
    cardio = Column(Boolean, comment="是否有心血管疾病")
    HeartDisease = Column(Boolean, comment="是否有心脏病")
    Risk = Column(Float, comment="风险评分")
    DEATH_EVENT = Column(Boolean, comment="是否死亡事件")
    time = Column(Date, comment="时间")
    ai_report_result = Column(JSON, comment="AI报告结果（JSON格式）")
